### Create appApplication level status
POST localhost:8081/api/v1/app-application-level-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc0NDY4NjQsImlkIjoiMzI1YTRmZmQ4ZDAyYjQwYTAxOGQwODIwMTE5YTA0NGUiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxNyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HLFJPTEVfQ09OU1VMVElOR19NQU5BR0VSIiwiZXhwIjoxNzA4MDUxNjY0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.U8KddPL5w4TL_jWLkJTf7q2QZV99ucn_0apIKiAtG4CAprM6rdTZTw7jBc6Qe8yjuMCyhhKWk4OOggpT9YA-zg

{
  "appApplicationId": "8080b7ef8bae722c018bae85c0cf0002",
  "consultingStepLevelId": "8080b7ef8bae722c018bae8a39560005",
  "applicationStepLevelStatus": "PAYMENT",
  "deadline": "2023-12-20",
  "amount": 1234,
  "description": "REVISION dasdas dasdme dasda sd"
}

### Create appApplication level status PROD
POST localhost:8085/api/v1/app-application-level-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc0NDY4NjQsImlkIjoiMzI1YTRmZmQ4ZDAyYjQwYTAxOGQwODIwMTE5YTA0NGUiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxNyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HLFJPTEVfQ09OU1VMVElOR19NQU5BR0VSIiwiZXhwIjoxNzA4MDUxNjY0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.U8KddPL5w4TL_jWLkJTf7q2QZV99ucn_0apIKiAtG4CAprM6rdTZTw7jBc6Qe8yjuMCyhhKWk4OOggpT9YA-zg

{
  "appApplicationId": "325a4ffd8d7d68d7018d7dfa4d78002f",
  "consultingStepLevelId": "325a4ffd8d7f1f57018d7f2f7cf1002e",
  "applicationStepLevelStatus": "PAYMENT",
  "amount": 1234,
  "description": "REVISION dasdas dasdme dasda sd"
}


### Update appApplication level status (check)
PUT localhost:8081/api/v1/app-application-level-status/402880e48ba39d5d018ba3a04d6e0005
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyNTM4MzcsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODU4NjM3LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.ZpqpywVfdMXov5S17ZtxLfLWIyPAkVHp4xVhTjU7TuUtcZlB5DhH56yd1DYBJzO0wubahhQA6D7NcjPkg1VLHw

{
  "description": "REVISION dasdas dasdme dasda sd",
  "deadline": "2023-11-06"
}


### Update appApplication level status (check)
GET localhost:8081/api/v1/app-application-level-status/enum/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDMxNjUzNDUsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDM3NzAxNDUsImlzcyI6IkphdmEgYmFja2VuZCJ9.68eoQlS4TBI7DKeLEnO1gq5BdLXB-tDO7qODP4p4JQPzwpQuwM76GXxJGENcdtdCjsJ5L6fmMd2rXi1L_wHrhw

