### Create appApplication for students
POST localhost:8081/api/v1/app-application
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTg0NzM1OTQsImlkIjoiNDAyODgwZTQ4Yjc0ZTliZDAxOGI3NGVhMmJmMDAwMDAiLCJwaG9uZSI6Ijk5ODkzMDY3MTQyMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk5MDc4Mzk0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.AGfQAfCUdPQ4hgtkXc6td06rh_Jfsdic29k0VhTv7Y5UhBEmBxaFm0kUDvJjWyWQVwo645fl1rG0aZJGpo1EHg

{
  "consultingId":"402880e48b74e6c8018b74e864c70004",
  "universityId": 1
}

### Filter appApplication for students
POST localhost:8081/api/v1/app-application/adm/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTgwNTgxNTcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTg2NjI5NTcsImlzcyI6IkphdmEgYmFja2VuZCJ9.fAVv-pU6VpSvvAWXXOkZg_rjcI0HrIog4VGXBitKQAcf2k7tNoSggb5MGcq8kk6T1Xcl4x09G0frLUA5NCXmlw

{
  "studentName" : "Maxmud"
}


### Get  appApplication for student
GET localhost:8081/api/v1/app-application/student
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTc4NzIxMTQsImlkIjoiNDAyODgwZTY4YjM4MzBhNTAxOGIzODMwZTAzMTAwMDAiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk4NDc2OTE0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.gToflpP99zz5o9G5jGCE5p3aDaSF_-DI4kaXscI-D3Aob4_CxrXfzPsUAKxVzaolHYv9LszcPpL9PeKm2OyT6A


### Filter appApplication for consulting
POST localhost:8081/api/v1/app-application/consulting/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTc4ODIyNDQsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk4NDg3MDQ0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.tBTNRXky-GZX6YY-ZLAWGHRAQ3_wK3g_xanGtmXAFteU6tQTtBEkxcNcEtIcKHBcSX68S-sckbrTf9NmsPcJmQ

{
  "studentName" : "Maxmud"
}

### Get AppAplication by id
GET localhost:8081/api/v1/app-application/402880ec8b5c4a16018b5c4ad0520000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTc4ODgxMjgsImlkIjoiNDAyODgwZTY4YjM4MzBhNTAxOGIzODMwZTAzMTAwMDAiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk4NDkyOTI4LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.vV3n4xs-II4K8Xjuf7ptYXHMrm24dBOKAJovT69XvNT_kpDdcW6-JaFzOM_caKULssM4SpVddDgTFt1ffKOsSw

### Change status appApplication for consulting
PUT localhost:8081/api/v1/app-application/change-status/402880e48b6ae66b018b6ae6ee1c0000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTc4OTM4MjAsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk4NDk4NjIwLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.BLbSoHreWkUuOWCkvDJIthv0ByttAGYfHGlJpFDtzCcnUEXKrzsp_WXLiWKsbmn7FCqzyRBRt9NOf-pdQp4nOQ

{
  "status" : "FINISHED"
}