### Create appApplication level status
POST localhost:8081/api/v1/app-application-level-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDMyMjYyMjIsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDM4MzEwMjIsImlzcyI6IkphdmEgYmFja2VuZCJ9.Z_uIJJxAmQssaGBYq6wi4GAjntTB0rg9mTsoCXj0VQhZIYA03l-I-ytWWcbYupkGvvNr4_ZByJS02i9xQ_9Rzg

{
  "appApplicationId": "8080b7ef8bae722c018bae85c0cf0002",
  "consultingStepLevelId": "8080b7ef8bae722c018bae8a39560005",
  "applicationStepLevelStatus": "PAYMENT",
  "deadline": "2023-12-20",
  "amount": 1234,
  "description": "REVISION dasdas dasdme dasda sd"
}


### Update appApplication level status (check)
PUT localhost:8081/api/v1/app-application-level-status/402880e48ba39d5d018ba3a04d6e0005
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyNTM4MzcsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODU4NjM3LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.ZpqpywVfdMXov5S17ZtxLfLWIyPAkVHp4xVhTjU7TuUtcZlB5DhH56yd1DYBJzO0wubahhQA6D7NcjPkg1VLHw

{
  "description": "REVISION dasdas dasdme dasda sd",
  "deadline": "2023-11-06"
}


### Update appApplication level status (check)
GET localhost:8081/api/v1/app-application-level-status/enum/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDMxNjUzNDUsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDM3NzAxNDUsImlzcyI6IkphdmEgYmFja2VuZCJ9.68eoQlS4TBI7DKeLEnO1gq5BdLXB-tDO7qODP4p4JQPzwpQuwM76GXxJGENcdtdCjsJ5L6fmMd2rXi1L_wHrhw

