###------------------------------------------------- Student

### Create appApplication
POST localhost:8081/api/v1/app-application
Content-Type: application/json
Authorization: Bearer {{studentToken}}

{
  "consultingId": "2c9c70818c1abd87018c1abf20590004",
  "universityId": 1
}

### AppApplication list for Student. Web
GET localhost:8081/api/v1/app-application/student
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDE3MDU5MTAsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTU0Njg2MzAwMjgiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzAyMzEwNzEwLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.5Ud7WilRDxCZ4IQSM3dtD4t53-8h7jNfj-DYQP8xTPhptgVRVljER701Dgya5l6yc9EKM24ttbxlU9cVqKSOQQ


### Get application consulting list for student . Mobile
GET localhost:8081/api/v1/app-application/mobile/student/consulting
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDE2NzM0MjcsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTU0Njg2MzAwMjgiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzAyMjc4MjI3LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.jae4JQJQrPa_25fB7WAaZ7IfPDaKgMAMAXyrdNeU754b29jP5bCc3IwlAaSSQeHis-XnBJgDB-onGBls6cT-9Q


### Filter Student AppApplicationUniversity list by consulting id. Mobile
GET localhost:8081/api/v1/app-application/mobile/student/8080b7ef8ba46236018bae4b30940021/university
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDEzMjY5OTUsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTU0Njg2MzAwMjgiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzAxOTMxNzk1LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.wToy-Ps2-89rETT2LtmIGeerxtB5oUbzAXcAqKknx6HvobZQVsmUuHw4KIhHVJJpima-5WabW2fzGcOd5V5q5A

###------------------------------------------------- Consulting

### Filter AppApplicationList for Consulting. Web
POST localhost:8081/api/v1/app-application/consulting/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI0NTEzMDksImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDMwNTYxMDksImlzcyI6IkphdmEgYmFja2VuZCJ9.kvMDX5nk5-8fuLHMrOu6HbUrtTCE_pHm1CU5ljA4nb8E_q5mwgXbavjWBfL4mn9TRKFJdnxYTAoMIPfdwQ4fLw

{

}


### Change appApplication status as consulting
PUT localhost:8081/api/v1/app-application/change-status/402880e88ba2ae64018ba2b330120000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyNDk4MjEsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODU0NjIxLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.pdfylAqfKB9DYcDVUl1Bca2NCpQmDcxrCfsqhLw841PlxFAKiamMqfBYTAWdkmpw4qvbWXcVjSIEy1LYVX8a-w

{
  "status": "STARTED"
}

### Update applicaiont tariff
POST localhost:8081/api/v1/app-application/consulting/402880e88ba2ae64018ba2b330120000/tariff
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyNDk4MjEsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODU0NjIxLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.pdfylAqfKB9DYcDVUl1Bca2NCpQmDcxrCfsqhLw841PlxFAKiamMqfBYTAWdkmpw4qvbWXcVjSIEy1LYVX8a-w
Content-Type: application/json

{
  "tariffId": "402880e88ba26b18018ba27083d00007"
}

### Update applicaiont consultingStep
POST localhost:8081/api/v1/app-application/consulting/402880e88ba2ae64018ba2b330120000/step
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyNDk4MjEsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODU0NjIxLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.pdfylAqfKB9DYcDVUl1Bca2NCpQmDcxrCfsqhLw841PlxFAKiamMqfBYTAWdkmpw4qvbWXcVjSIEy1LYVX8a-w

{
  "consultingStepId": "402880e88ba27c4c018ba27cddfc0000"
}

### Get Application student list by countryId for Consulting. Mobile
POST localhost:8081/api/v1/app-application/mobile/consulting/university/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI0NTEzMDksImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDMwNTYxMDksImlzcyI6IkphdmEgYmFja2VuZCJ9.kvMDX5nk5-8fuLHMrOu6HbUrtTCE_pHm1CU5ljA4nb8E_q5mwgXbavjWBfL4mn9TRKFJdnxYTAoMIPfdwQ4fLw

{
}


###------------------------------------------------- Genral
### Get AppAplication by id
GET localhost:8081/api/v1/app-application/8080b7ef8bae722c018bae85c0cf0002
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI0NTEzMDksImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDMwNTYxMDksImlzcyI6IkphdmEgYmFja2VuZCJ9.kvMDX5nk5-8fuLHMrOu6HbUrtTCE_pHm1CU5ljA4nb8E_q5mwgXbavjWBfL4mn9TRKFJdnxYTAoMIPfdwQ4fLw




###------------------------------------------------- ADMIN
### Filter appApplication for admin
POST localhost:8081/api/v1/app-application/adm/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTgwNTgxNTcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTg2NjI5NTcsImlzcyI6IkphdmEgYmFja2VuZCJ9.fAVv-pU6VpSvvAWXXOkZg_rjcI0HrIog4VGXBitKQAcf2k7tNoSggb5MGcq8kk6T1Xcl4x09G0frLUA5NCXmlw

{
  "studentName": "Maxmud"
}



