### Upload a file
POST http://localhost:8081/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI2NDYwODUsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDMyNTA4ODUsImlzcyI6IkphdmEgYmFja2VuZCJ9.syDjFO_kLxbDQMicUnFbpcZG_r3zJqGv_Xq7V9y6D2B6oOqvkMko2s8yiwl_mrV_Kc4eMQ4Y2AuCO211sXQFlQ


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testjon.jpg"

< C:\Users\Bobur_Jumaniyazov\Desktop\images\testjon.jpg

### Get all attach
GET http://localhost:8081/api/v1/attach/get-all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g



###Deleted attach
DELETE http://localhost:8081/api/v1/attach/delete/402880e88ad72df4018ad72e0bfd0000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g


### Upload a file to application step level
POST http://localhost:8081/api/v1/attach/upload/application/step_level?stepLevelId=402880e48ba33c9b018ba33da92e0002&attachType=PASSPORT
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkwMjc5NDMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTk2MzI3NDMsImlzcyI6IkphdmEgYmFja2VuZCJ9.tIu0zoHsm1UWRf4xhE2_rfv_XX4FeB-5D3UQ61ubfLduetj_kMRlnp-Lcw9u9Fu2iY9Di6QBXeUyfJOS-jIRwQ


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="dimplom-data.pdf"

< C:\Users\Bobur_Jumaniyazov\Desktop\images\testjon.jpg

### DOWNLOAD BY ID
GET http://localhost:8081/api/v1/attach/download/4028abb98bc471a5018bc475bbad0000/1.jpg



### Upload file to simple-message as consulting
POST http://localhost:8081/api/v1/attach/upload/simp-message/consulting?applicationId=8080b7ef8bae722c018bae85c0cf0002&attachType=OTHER
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI4ODQ0MjMsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDM0ODkyMjMsImlzcyI6IkphdmEgYmFja2VuZCJ9.pEx_fvdrygv8QhSC3mmq5MnJM8U1co_J9vQxUvRimmLtOF1-zmDCSjmaiI5YxHDsr9dcEQf8mW0tLxFvJLPcDw


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testjon.jpg"

< C:\Users\Bobur_Jumaniyazov\Desktop\images\testjon.jpg