### Register
POST http://localhost:8081/api/v1/auth/profile/registration
Content-Type: application/json


{
  "name": "Bekzod",
  "surname": "Nosirov",
  "phoneNumber": "+998944497397",
  "password": "123456"
}

### Profile sms verification login
POST http://localhost:8081/api/v1/auth/profile/registration/verification
Content-Type: application/json


{
  "phone": "+998944497397",
  "code": "55275"
}
### Consulting login
POST http://localhost:8081/api/v1/auth/consulting/login
Content-Type: application/json


{
  "phone": "+998972322903",
  "password": "74521"
}

### Profile login
POST http://localhost:8081/api/v1/auth/profile/login
Content-Type: application/json


{
  "phone": "+998938080831",
  "password": "123456"
}
### authenticate USER
POST http://localhost:8081/api/v1/auth/authenticate
Content-Type: application/json

{
  "phone": "998915721213",
  "password": "123456"
}

### authenticate ADMIN
POST http://178.218.207.96:8081/api/v1/auth/authenticate
Content-Type: application/json

{
  "phone": "998972322903",
  "password": "Sarvar03"
}

### authenticate USER
POST http://localhost:8081/api/v1/auth/authenticate
Content-Type: application/json

{
  "phone": "998944497397",
  "password": "45347"
}


