### Register
POST http://localhost:8081/api/v1/auth/profile/registration
Content-Type: application/json

{
  "name": "asd",
  "surname": "asd",
  "phoneNumber": "998915721213",
  "password": "123456",
  "nickName": "bigman",
  "countryId": 1,
  "address": "Toshkent viloyati",
  "gender": "MALE",
  "photo_id": "402880e78b7093f0018b70a640840006"
}


### Register 2
POST http://api.app.mazgi.uz/api/v1/auth/profile/registration
Content-Type: application/json

{
  "name": "Bilolchik",
  "surname": "To'xtamurodov",
  "phoneNumber": "998930671423",
  "password": "123456",
  "nickName": "bilolchik",
  "countryId": 1,
  "address": "Toshkent viloyati",
  "gender": "MALE"
}


### Profile sms verification login
POST http://localhost:8081/api/v1/auth/profile/registration/verification
Content-Type: application/json


{
  "phone": "998915721213",
  "code": "11111"
}
### Consulting login
POST http://localhost:8081/api/v1/auth/consulting/login
Content-Type: application/json

{
  "phone": "998997795710",
  "password": "8yrjdt"
}

### Profile login
POST http://localhost:8081/api/v1/auth/profile/login
Content-Type: application/json


{
  "phone": "998915721213",
  "password": "123456"
}

### Reset password for profile
POST http://localhost:8081/api/v1/auth/profile/reset-password
Content-Type: application/json

{
  "phone": "998997795710"
}

### Reset password confirm for profile
PUT http://localhost:8081/api/v1/auth/profile/reset/confirm
Content-Type: application/json

{
  "phone": "998997795710",
  "smsCode": "71824",
  "newPassword": "123457",
  "repeatNewPassword": "123457"

}


### Reset password for consulting
POST http://localhost:8081/api/v1/auth/consulting/reset-password
Content-Type: application/json

{
  "phone": "998997795710"
}

### Reset password confirm for consulting
PUT http://localhost:8081/api/v1/auth/consulting/reset/confirm
Content-Type: application/json

{
  "phone": "998997795710",
  "smsCode": "66331",
  "newPassword": "123457",
  "repeatNewPassword": "123457"

}

### authenticate ADMIN
POST http://localhost:8081/api/v1/auth/profile/login
Content-Type: application/json

{
  "phone": "998938080831",
  "password": "123456"
}

### PROD authenticate ADMIN
POST http://api.app.mazgi.uz/api/v1/auth/profile/login
Content-Type: application/json

{
  "phone": "998938080831",
  "password": "123456"
}

### Exist Profile NickName
GET http://localhost:8081/api/v1/auth
Content-Type: application/json

{
  "nickName" : "maxmud123"
}

