### Register
POST http://localhost:8081/api/v1/consulting/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MTc2NzQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MjI0NzQsImlzcyI6IkphdmEgYmFja2VuZCJ9.aMV2EuvcUuXQjckcq1Yzzx7GbS4IiyQ0T4-9OU-qtmK-XTlJcuSk1CCJJGdqpuPq0Mli7p3faRyuoE9pZM1ZcA


{
  "name": "Brain consulting",
  "phone": "998997795710",
  "password": "123456",
  "address": "Toshkent shahri"
}
