### CREATE
POST http://localhost:8081/api/v1/consulting-step-level/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTg4MzEwMTgsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5NDM1ODE4LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.dCsiVLyrL4oOlBQ7x-v3ClB9AuA3EB7Nlj5AFzQYNWGLZfeTFo0ATQi4Qt_P1_oRCbLfwo-Nk_l7J357KBQg2g
Content-Type: application/json

{
  "nameUz": "asd",
  "nameRu": "asda",
  "nameEn": "asdad",
  "orderNumber": 3,
  "description": "Hi everyone",
  "consultingStepId": "402880e68b8ac642018b8ac738760000"
}

### DELETE
DELETE http://localhost:8081/api/v1/consulting-step-level/402880e88b146525018b146535e60000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NTAxNzMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc0NTQ5NzMsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qjee4qBBXsaDDhY7vvSj9CNKuUDb6eI5LKzi4CO2kATx0j70IFxu6XTAMnjmjgFCE9rpNwcz-xUOZMKUZL7OJw

### UPDATE
PUT http://localhost:8081/api/v1/consulting-step-level/402880e88b1463fd018b1464109b0000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NTAxNzMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc0NTQ5NzMsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qjee4qBBXsaDDhY7vvSj9CNKuUDb6eI5LKzi4CO2kATx0j70IFxu6XTAMnjmjgFCE9rpNwcz-xUOZMKUZL7OJw
Content-Type: application/json

{
  "nameUz": "asd",
  "nameRu": "asda123",
  "nameEn": "asdad",
  "orderNumbers": "11",
  "description": "Hi everyone",
  "consultingStepId": "402880e88b143072018b1430d6480000",
  "prtId": "402880e88b142466018b14247bdc0000"
}

### GET BY CONSULTING ID
GET http://localhost:8081/api/v1/consulting-step-level/402880e88b143072018b1430d6480000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NTAxNzMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc0NTQ5NzMsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qjee4qBBXsaDDhY7vvSj9CNKuUDb6eI5LKzi4CO2kATx0j70IFxu6XTAMnjmjgFCE9rpNwcz-xUOZMKUZL7OJw
