### Create
POST http://localhost:8081/api/v1/consulting-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM0MTM5OTYsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDQwMTg3OTYsImlzcyI6IkphdmEgYmFja2VuZCJ9.sDwfF3TUNPd37Imeh6AE4jUeqJ6jSDRK5amzfQJ183mzagyg_HdIv059N-yoKT_mstOMxvoj2Y6jUsGlv80yMw

{
  "name": "Sarvar",
  "surname": "Mukhtarov",
  "password": "123456",
  "phone": "998972322904",
  "address": "Toshkent, Chilonzor 19"
}

### Update
PUT http://localhost:8081/api/v1/consulting-profile/4028f80a8c9b91e3018c9b92c2940000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM0MTM5OTYsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDQwMTg3OTYsImlzcyI6IkphdmEgYmFja2VuZCJ9.sDwfF3TUNPd37Imeh6AE4jUeqJ6jSDRK5amzfQJ183mzagyg_HdIv059N-yoKT_mstOMxvoj2Y6jUsGlv80yMw

{
  "name": "Sarvar1",
  "surname": "Mukhtarov1",
  "address": "Toshkent, Chilonzor 20"
}

### delete
DELETE http://localhost:8081/api/v1/consulting-profile/4028f80a8c9b86ab018c9b86d5290000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM0MTM5OTYsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDQwMTg3OTYsImlzcyI6IkphdmEgYmFja2VuZCJ9.sDwfF3TUNPd37Imeh6AE4jUeqJ6jSDRK5amzfQJ183mzagyg_HdIv059N-yoKT_mstOMxvoj2Y6jUsGlv80yMw


### FIND ALL
GET http://localhost:8081/api/v1/consulting-profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM0MTM5OTYsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDQwMTg3OTYsImlzcyI6IkphdmEgYmFja2VuZCJ9.sDwfF3TUNPd37Imeh6AE4jUeqJ6jSDRK5amzfQJ183mzagyg_HdIv059N-yoKT_mstOMxvoj2Y6jUsGlv80yMw

### Update status
PUT http://localhost:8081/api/v1/consulting-profile/update-status/4028f80a8c9b86ab018c9b86d5290000?status=ACTIVE
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM0MTM5OTYsImlkIjoiNDAyODgwZTU4YzYxZjFmMDAxOGM2MWYzNjBhMTAwMDIxMSIsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZXMiOiJST0xFX0NPTlNVTFRJTkcsUk9MRV9DT05TVUxUSU5HX01BTkFHRVIiLCJleHAiOjE3MDQwMTg3OTYsImlzcyI6IkphdmEgYmFja2VuZCJ9.sDwfF3TUNPd37Imeh6AE4jUeqJ6jSDRK5amzfQJ183mzagyg_HdIv059N-yoKT_mstOMxvoj2Y6jUsGlv80yMw

### Update lang
PUT http://localhost:8081/api/v1/consulting-profile/update-lang?lang=uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDQ3ODI5MTcsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTU0Njg2MzAwMjgiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzA1Mzg3NzE3LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.gMwCSdqZWyvOD62ppMMb3A0mkzLXZyVM_8WPZzImBlyyLYbAYmSOnz3WTyuqm4-K8ndOixXN43xkgDdsPcGLXw

### Find by ConsultingId As ADMIN
GET http://localhost:8081/api/v1/consulting-profile/adm/consulting/8080b7ef8ba46236018bae4b30940021
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDUzODkxMTAsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDU5OTM5MTAsImlzcyI6IkphdmEgYmFja2VuZCJ9.Nf8QZS4wyuV3tnPWMlY_RLiMsOL2WQMFQ6wRGvT1yoUQmNwT-Z0sFrv4anSHbWLH8ZesnWiI7zMkC7X39-AC8g