### Register
POST http://localhost:8081/api/v1/consulting/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU3Mjc1ODcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTYzMzIzODcsImlzcyI6IkphdmEgYmFja2VuZCJ9.NhJieki95nxraA79ngXfGvKi1D0TsLaewMzl6e8NEgf_Y1L-TFbabgPpqbNGIR3nfZXlGtYttTF9L27fIrsylg


{
  "name": "Brain consulting",
  "phone": "998997795710",
  "password": "123456",
  "address": "Toshkent shahri"
}
