### CREATE
POST http://localhost:8081/api/v1/consulting-step-level
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyMzczMTMsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODQyMTEzLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.q3r1HgdjAAz1f-TAaulTn9yqwjDCmajQnFzDgfpSF2vWsXw4I14zDoc2kZipMqP06jpW4X6Rgn54xi8N8LpvOA
Content-Type: application/json

{
  "nameUz": "2-Bosqish",
  "nameRu": "2-Bosqish",
  "nameEn": "2-Bosqish",
  "orderNumber": 2,
  "description": "Hi everyone",
  "consultingStepId": "402880e88ba27c4c018ba27cddfc0000"
}

### DELETE
DELETE http://localhost:8081/api/v1/consulting-step-level/402880e88b146525018b146535e60000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NTAxNzMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc0NTQ5NzMsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qjee4qBBXsaDDhY7vvSj9CNKuUDb6eI5LKzi4CO2kATx0j70IFxu6XTAMnjmjgFCE9rpNwcz-xUOZMKUZL7OJw

### UPDATE
PUT http://localhost:8081/api/v1/consulting-step-level/402880e88b1463fd018b1464109b0000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NTAxNzMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc0NTQ5NzMsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qjee4qBBXsaDDhY7vvSj9CNKuUDb6eI5LKzi4CO2kATx0j70IFxu6XTAMnjmjgFCE9rpNwcz-xUOZMKUZL7OJw
Content-Type: application/json

{
  "nameUz": "asd",
  "nameRu": "asda123",
  "nameEn": "asdad",
  "orderNumbers": "11",
  "description": "Hi everyone",
  "consultingStepId": "402880e88b143072018b1430d6480000",
  "prtId": "402880e88b142466018b14247bdc0000"
}

### Get level list by stepId
GET http://localhost:8081/api/v1/consulting-step-level/step/402880e88ba27c4c018ba27cddfc0000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkyMzczMTMsImlkIjoiNDAyODgwZTg4YmEyNmIxODAxOGJhMjZkYTI0NzAwMDIiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5ODQyMTEzLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.q3r1HgdjAAz1f-TAaulTn9yqwjDCmajQnFzDgfpSF2vWsXw4I14zDoc2kZipMqP06jpW4X6Rgn54xi8N8LpvOA
