### CONSULTING COMMENT CREATE
POST http://localhost:8081/api/v1/consulting/comment/402880e48b74e6c8018b74e864c70004
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTg0NzM1OTQsImlkIjoiNDAyODgwZTQ4Yjc0ZTliZDAxOGI3NGVhMmJmMDAwMDAiLCJwaG9uZSI6Ijk5ODkzMDY3MTQyMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk5MDc4Mzk0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.AGfQAfCUdPQ4hgtkXc6td06rh_Jfsdic29k0VhTv7Y5UhBEmBxaFm0kUDvJjWyWQVwo645fl1rG0aZJGpo1EHg

{
  "content": "Salom3"
}

### CONSULTING GET BY ID
GET http://localhost:8081/api/v1/consulting/comment/402880e48b6adf67018b6ae1bb810004

### FILTER
POST http://localhost:8081/api/v1/consulting/comment/filter
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTg0NzM3NDMsImlkIjoiNDAyODgwZTQ4Yjc0ZTZjODAxOGI3NGU3MTk4MTAwMDAiLCJwaG9uZSI6Ijk5ODkzMDY3MTQyNiIsInJvbGVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY5OTA3ODU0MywiaXNzIjoiSmF2YSBiYWNrZW5kIn0.hnfz6gKJZS8wYjM9qiL422oOWYFb237dmwSCpbJeBfTktMd4heKJBiMvDLtpcaYulkR0t_2Ur_u349lgvTIGeQ
Content-Type: application/json

{
  "studentId": "402880e48b74e9bd018b74ea2bf00000",
  "consultingId": "402880e48b74e6c8018b74e864c70004",
  "fromCreatedDate": "2023-10-27",
  "toCreatedDate": "2023-10-29"
}