### Create consulting tariff
POST http://localhost:8081/api/v1/consulting-tariff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTgwNTQyNjMsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk4NjU5MDYzLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.M860WN_YL_Ogja_RG0IlCHTb63ZtLs8oGJEtyZE33sLg9QU_TZh-AH7VMcWOd2khXwlQ_yLZJr-7h0LDk59-aQ

{
  "descriptionUz": "Brain uz",
  "descriptionRu": "Brain ru",
  "descriptionEn": "Brain en",
  "name": "Yaxshi Ta'riff",
  "price": 5600,
  "consultingId": "402880e68b38493f018b384a38a60002",
  "status": "ACTIVE",
  "tariffType": "CONSULTING",
  "order": 3
}


### Get Consulting Tariff By Id
GET http://localhost:8081/api/v1/consulting-tariff/402880e78b140640018b14191ff80003
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NDkxMzEsImlkIjoiNDAyODgwZTc4YjE0MDY0MDAxOGIxNDA4MTU1NzAwMDEiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk3NDUzOTMxLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.4SfS6njqybDasUv1gZLtaabtMGuw9fPFsVvYffqQRu3gFnv87BSD3OmYtv_vxTkXXSI-OINBIgKlG8C5Mb-iBQ
Accept-Language: en

### Update Consulting Tariff
PUT http://localhost:8081/api/v1/consulting-tariff/402880ec8b5bea14018b5bec38040000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTgwNTQyNjMsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk4NjU5MDYzLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.M860WN_YL_Ogja_RG0IlCHTb63ZtLs8oGJEtyZE33sLg9QU_TZh-AH7VMcWOd2khXwlQ_yLZJr-7h0LDk59-aQ
Content-Type: application/json

{
  "descriptionUz": "Brain uz1",
  "descriptionRu": "Brain ru1",
  "descriptionEn": "Brain en1",
  "name": "Surish kerak Ta'rif rejasi",
  "price": 5600,
  "status": "ACTIVE",
  "tariffType": "CONSULTING",
  "order": 2
}

###
DELETE http://localhost:8081/api/v1/consulting-tariff/c0e0008b-ef79-4363-bcd0-a734e14dbfd9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkwMDU0NjEsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5NjEwMjYxLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.Df2I9ziFNJFfWsFNpBVRVCVHKMg65rAsK3Ek58WJbjtvaQrHpgG1Dw0ywju78IjLCpm81ZucEZGjgVIUFDt6Fg

### Get Consulting Tariff By  Consulting Id
GET http://localhost:8081/api/v1/consulting-tariff/consulting/402880e68b38493f018b384a38a60002
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTkwMDU0NjEsImlkIjoiNDAyODgwZTY4YjM4NDkzZjAxOGIzODRhMzhhNjAwMDIiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk5NjEwMjYxLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.Df2I9ziFNJFfWsFNpBVRVCVHKMg65rAsK3Ek58WJbjtvaQrHpgG1Dw0ywju78IjLCpm81ZucEZGjgVIUFDt6Fg
Accept-Language: en



### Get Consulting Tariff List Template tariff
GET http://localhost:8081/api/v1/consulting-tariff/template-list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTcxOTYyNzMsImlkIjoiNDAyODgwZTk4YjI4YzY0NTAxOGIyOGM2ZmMyMTAwMDEiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk3ODAxMDczLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.20B1jC4Yp6sJyId2xVYdN2892woWgRuXGF8g-Eq7sb0FCby0NgWiwL-j8_yiYrGOLBgrrCsexjtO6mm2p-sehQ
Accept-Language: en

