### CREATE CONSULTING STEP
POST http://localhost:8081/api/v1/consulting-step/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTcyMDU2OTQsImlkIjoiNDAyODgwZTQ4YjI5NTMwZDAxOGIyOTU1Yzk0MDAwMDEiLCJwaG9uZSI6Ijk5ODk0NDQ5NzM5NyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk3ODEwNDk0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.uw4eHtrB8r9N6JLz6w_HcCN14s6Tcsna6FVXTwvkUdFPAhppOy3_4-P9kqEIVdpr3rYMzbSxrFiib3EoNInsqw
Content-Type: application/json

{
  "name": "bbb",
  "description": "bbb",
  "orderNumber": "2"
}

### DELETE CONSULTING STEP
DELETE http://localhost:8081/api/v1/consulting-step/402880ed8b1e50a8018b1e50d17e0000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTcwMjE1NjQsImlkIjoiNDAyODgwZWQ4YjFlNWMwMjAxOGIxZTVkZTk4NTAwMDYiLCJwaG9uZSI6Ijk5ODkzMDY3MTQyMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk3NjI2MzY0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.4aqgoAqKdXRz3zSRq0yyZi7LRp6NWwjmtbbtaEzF8YzJgbMHpb8HsZvZ10Mix5gMtKs0xGf_TNf9wO_-qlZEUw

### UPDATE CONSULTING STEP
PUT http://localhost:8081/api/v1/consulting-step/402880ed8b1e0d96018b1e0e34100001
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY4NTAxNzMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc0NTQ5NzMsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qjee4qBBXsaDDhY7vvSj9CNKuUDb6eI5LKzi4CO2kATx0j70IFxu6XTAMnjmjgFCE9rpNwcz-xUOZMKUZL7OJw
Content-Type:application/json

{
  "name": "asdad",
  "orderNumbers": "123",
  "description": "Hi everyone"
}


### Get consulting step list
GET http://localhost:8081/api/v1/consulting-step/consulting
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTcyMDU2OTQsImlkIjoiNDAyODgwZTQ4YjI5NTMwZDAxOGIyOTU1Yzk0MDAwMDEiLCJwaG9uZSI6Ijk5ODk0NDQ5NzM5NyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNjk3ODEwNDk0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.uw4eHtrB8r9N6JLz6w_HcCN14s6Tcsna6FVXTwvkUdFPAhppOy3_4-P9kqEIVdpr3rYMzbSxrFiib3EoNInsqw
Content-Type:application/json
