### GET Continent list
GET http://localhost:8081/api/v1/continent/public/get-all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY2NzYwOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTcyODA4OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.fArkUh1SlE2pwvNsOYwn05mXlHZRpw3Eo6E6WIxFFoJS9gL4LszH5SnuklJtZzJ64wa09Vk8kV0Rz4q0OO1MBA
Accept-Language: uz




###CREATE Continent
POST http://localhost:8081/api/v1/continent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY2NzYwOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTcyODA4OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.fArkUh1SlE2pwvNsOYwn05mXlHZRpw3Eo6E6WIxFFoJS9gL4LszH5SnuklJtZzJ64wa09Vk8kV0Rz4q0OO1MBA


{
  "nameUz": "string",
  "nameRu": "string",
  "nameEn": "string",
  "order": 6
}


###UPDATE Continent
PUT http://localhost:8081/api/v1/continent/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY2NzYwOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTcyODA4OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.fArkUh1SlE2pwvNsOYwn05mXlHZRpw3Eo6E6WIxFFoJS9gL4LszH5SnuklJtZzJ64wa09Vk8kV0Rz4q0OO1MBA

{
  "nameUz": "Узбек",
  "nameEn": "Uzbek",
  "nameRu": "Узбеки",
  "order": 10
}


###DELETE Continent
DELETE http://localhost:8081/api/v1/continent/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY2NzYwOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTcyODA4OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.fArkUh1SlE2pwvNsOYwn05mXlHZRpw3Eo6E6WIxFFoJS9gL4LszH5SnuklJtZzJ64wa09Vk8kV0Rz4q0OO1MBA






