### GET Country
GET http://localhost:8081/api/v1/country/public/get-all
Accept-Language: uz




###CREATE COUNTRY
POST http://localhost:8081/api/v1/country
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU5MDAzODYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY1MDUxODYsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qgrd7CvTLHW2vLZf7sDxq40bGdTWNSoujTx8tqA4xvEVMGFahK302HN4ig4ZVL1nCI4qkYNDmR8ikO1SiGVr-A


{
  "nameUz": "string",
  "nameRu": "string",
  "nameEn": "string"
}


###UPDATE COUNTRY
PUT http://localhost:8081/api/v1/country/50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU5MDAzODYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY1MDUxODYsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qgrd7CvTLHW2vLZf7sDxq40bGdTWNSoujTx8tqA4xvEVMGFahK302HN4ig4ZVL1nCI4qkYNDmR8ikO1SiGVr-A

{
  "nameUz": "Узбек",
  "nameEn": "Uzbek",
  "nameRu": "Узбеки"
}


###DELETE COUNTRY
DELETE http://localhost:8081/api/v1/country/50
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU5MDAzODYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY1MDUxODYsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qgrd7CvTLHW2vLZf7sDxq40bGdTWNSoujTx8tqA4xvEVMGFahK302HN4ig4ZVL1nCI4qkYNDmR8ikO1SiGVr-A


###COUNTRY PAGINATION
GET http://localhost:8081/api/v1/country/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU5MDAzODYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY1MDUxODYsImlzcyI6IkphdmEgYmFja2VuZCJ9.Qgrd7CvTLHW2vLZf7sDxq40bGdTWNSoujTx8tqA4xvEVMGFahK302HN4ig4ZVL1nCI4qkYNDmR8ikO1SiGVr-A




