### Get admin dashboard data
GET http://localhost:8085/api/v1/app-application/adm/dashboard
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODQwMjksImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg1ODg4MjksImlzcyI6IkphdmEgYmFja2VuZCJ9.ECT6d_0WZQMB0RFjW2Z5XfhFLnaBhvOvQHoIslYTTuXnV_xbCw5QNTcy0EewrVfY91D8iPmj0cxrt2TEatMQRg