### Get all destination list
GET http://localhost:8081/api/v1/destination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDM4MjMwMjIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDQ0Mjc4MjIsImlzcyI6IkphdmEgYmFja2VuZCJ9.ZicLMtX2s3QdbbqJKCDelMOWvFRGqdCpUoA83jCWmnAulErMDZAYeup_jTGANiylQzXLb3mbLsFjHDp0spZHOQ


### Get by id destination
GET http://localhost:8081/api/v1/destination/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDIxOTYzMTcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDI4MDExMTcsImlzcyI6IkphdmEgYmFja2VuZCJ9.85WOkBcDWnF_3CwT8j262pPcrITREkiKmkg1Oe1wgipb-PlEBARZVUvXHIJqUA58E1pSgXZ76EZnTii9E8FSeA


### Get all destination list language
GET http://localhost:8081/api/v1/destination/language
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDM4MjMwMjIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDQ0Mjc4MjIsImlzcyI6IkphdmEgYmFja2VuZCJ9.ZicLMtX2s3QdbbqJKCDelMOWvFRGqdCpUoA83jCWmnAulErMDZAYeup_jTGANiylQzXLb3mbLsFjHDp0spZHOQ
Accept-Language: en

### Get by id destination  language
GET http://localhost:8081/api/v1/destination/language/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDIxOTYzMTcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDI4MDExMTcsImlzcyI6IkphdmEgYmFja2VuZCJ9.85WOkBcDWnF_3CwT8j262pPcrITREkiKmkg1Oe1wgipb-PlEBARZVUvXHIJqUA58E1pSgXZ76EZnTii9E8FSeA
Accept-Language: ru

### Get all page
GET http://localhost:8081/api/v1/destination/filter?
    page=1&
    size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDIxOTYzMTcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDI4MDExMTcsImlzcyI6IkphdmEgYmFja2VuZCJ9.85WOkBcDWnF_3CwT8j262pPcrITREkiKmkg1Oe1wgipb-PlEBARZVUvXHIJqUA58E1pSgXZ76EZnTii9E8FSeA


###CREATE destination
POST http://localhost:8081/api/v1/destination
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDM4MjMwMjIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDQ0Mjc4MjIsImlzcyI6IkphdmEgYmFja2VuZCJ9.ZicLMtX2s3QdbbqJKCDelMOWvFRGqdCpUoA83jCWmnAulErMDZAYeup_jTGANiylQzXLb3mbLsFjHDp0spZHOQ

{
  "nameUz": "Qirg'istonUZ 5",
  "nameRu": "Qirg'istonRU 5",
  "nameEn": "Qirg'istonEn 5",
  "attachId": "2c99f081959d525001959d5ac6460001",
  "orderNumber": 6,
  "showInMainPage": false
}

###UPDATE destination
PUT http://localhost:8081/api/v1/destination/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDM4MjMwMjIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDQ0Mjc4MjIsImlzcyI6IkphdmEgYmFja2VuZCJ9.ZicLMtX2s3QdbbqJKCDelMOWvFRGqdCpUoA83jCWmnAulErMDZAYeup_jTGANiylQzXLb3mbLsFjHDp0spZHOQ

{
  "nameUz": "Qozag'iston Update",
  "nameRu": "Qozag'iston Update",
  "nameEn": "Qozag'iston Update",
  "attachId": "2c99f081959d525001959d5ac6460001",
  "orderNumber": 2,
  "showInMainPage": false
}

### DELETE destination
DELETE http://localhost:8081/api/v1/destination/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDIxOTYzMTcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDI4MDExMTcsImlzcyI6IkphdmEgYmFja2VuZCJ9.85WOkBcDWnF_3CwT8j262pPcrITREkiKmkg1Oe1wgipb-PlEBARZVUvXHIJqUA58E1pSgXZ76EZnTii9E8FSeA

