### Create consulting
POST http://localhost:8081/api/v1/faculty
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nameUz": "Biznes  faculty uz",
  "nameEn": "Biznes faculty en",
  "nameRu": "Biznes faculty ru",
  "orderNumber": 1
}


### Update tariff
PUT http://localhost:8081/api/v1/faculty/402880ea8bf4eea3018bf4eec6960000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA2MjExOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDEyMjU5OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.PRqi9I9POMlmRxRLwrDaPW3fG2YZDZ0bPxB3eONim7E3ghTbswqzWsm-VQwPt67FecB9V_x3e6NzQZN8TesBPg

{
  "nameUz": "name uz3",
  "nameEn": "name en3",
  "nameRu": "name ru3"
}

### Get by id
GET http://localhost:8081/api/v1/faculty/402880ea8bf4eea3018bf4eec6960000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA2MjExOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDEyMjU5OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.PRqi9I9POMlmRxRLwrDaPW3fG2YZDZ0bPxB3eONim7E3ghTbswqzWsm-VQwPt67FecB9V_x3e6NzQZN8TesBPg


### Delete
DELETE http://localhost:8081/api/v1/faculty/402880ea8bf4eea3018bf4eec6960000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA2MjExOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDEyMjU5OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.PRqi9I9POMlmRxRLwrDaPW3fG2YZDZ0bPxB3eONim7E3ghTbswqzWsm-VQwPt67FecB9V_x3e6NzQZN8TesBPg


### Consulting filter public
POST http://localhost:8081/api/v1/faculty/filter/public
Content-Type: application/json

{
}

### Faculty tree
GET http://localhost:8081/api/v1/faculty/tree
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA2MjExOTQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDEyMjU5OTQsImlzcyI6IkphdmEgYmFja2VuZCJ9.PRqi9I9POMlmRxRLwrDaPW3fG2YZDZ0bPxB3eONim7E3ghTbswqzWsm-VQwPt67FecB9V_x3e6NzQZN8TesBPg

### Faculty sub
GET http://localhost:8081/api/v1/faculty/402880ea8bf4eea3018bf4eec6960000/sub







