### Create
GET https://api.scolaroconsult.uz/init/data/start?key=!a3(sdgdamdq.ewr,!a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDUyMjI1MzcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDU4MjczMzcsImlzcyI6IkphdmEgYmFja2VuZCJ9.uVgNOO_ZW2ltU0gNDVfYPYxGsW6rkfXA7c470HxIdSd6NUJNBzdpy2knJ6lOvwQVUlNiZUCW_BBqgWxZdAk0WA


### Create grant
GET https://api.scolaroconsult.uz/init/data/start-grant?key=!a3(sdgdamdq.ewr,!a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDUyMjI1MzcsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDU4MjczMzcsImlzcyI6IkphdmEgYmFja2VuZCJ9.uVgNOO_ZW2ltU0gNDVfYPYxGsW6rkfXA7c470HxIdSd6NUJNBzdpy2knJ6lOvwQVUlNiZUCW_BBqgWxZdAk0WA
