### Create
GET http://localhost:8085/init/data/start?key=.
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDIyOTA0NzQsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDI4OTUyNzQsImlzcyI6IkphdmEgYmFja2VuZCJ9.-kG3GWB3-k2HHo7GXbe1q08-Ph4-hXY_Mo0HBZRgHYalI-PJT0ZPby_4ogscwqnalZW6yJYoEcX6yGJTgr0Eqg
