### Update profile
PUT http://localhost:8081/api/v1/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDUyNTUsImlkIjoiNDAyODgwZTg4YWQ1ZGMyZTAxOGFkNWRlNDQyNTAwMDAiLCJwaG9uZSI6Iis5OTg5NDQ0OTczOTciLCJyb2xlcyI6IlJPTEVfU1RVREVOVCIsImV4cCI6MTY5NjQxMDA1NSwiaXNzIjoiSmF2YSBiYWNrZW5kIn0.6g0Vy-tuFrnRLL4zfqRRuJepcz6nVS5QvIUSwZAC0iLkUg8tly0TOSGlvN24QVUPZDs71knrccwn75miGh-FrA

{
  "name": "Bekzodjon",
  "surname": "Nosirovvv"

}


### Get profile by id
GET http://localhost:8081/api/v1/profile/402880e88ad5dc2e018ad5de4425000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g





### Get profile filter
GET http://localhost:8081/api/v1/profile/filter
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g
Content-Type: application/json


{
  "fromCreatedDate": "2023-08-08",
  "toCreatedDate": "2023-09-28"
}


### Delete profile
DELETE http://localhost:8081/api/v1/profile/402880e88ad5dc2e018ad5de44250000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g


### Update profile phone
PUT http://localhost:8081/api/v1/profile/update-phone?phone=998949092299
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDUyNTUsImlkIjoiNDAyODgwZTg4YWQ1ZGMyZTAxOGFkNWRlNDQyNTAwMDAiLCJwaG9uZSI6Iis5OTg5NDQ0OTczOTciLCJyb2xlcyI6IlJPTEVfU1RVREVOVCIsImV4cCI6MTY5NjQxMDA1NSwiaXNzIjoiSmF2YSBiYWNrZW5kIn0.6g0Vy-tuFrnRLL4zfqRRuJepcz6nVS5QvIUSwZAC0iLkUg8tly0TOSGlvN24QVUPZDs71knrccwn75miGh-FrA




### Update phone verification
PUT http://localhost:8081/api/v1/profile/phone-verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDUyNTUsImlkIjoiNDAyODgwZTg4YWQ1ZGMyZTAxOGFkNWRlNDQyNTAwMDAiLCJwaG9uZSI6Iis5OTg5NDQ0OTczOTciLCJyb2xlcyI6IlJPTEVfU1RVREVOVCIsImV4cCI6MTY5NjQxMDA1NSwiaXNzIjoiSmF2YSBiYWNrZW5kIn0.6g0Vy-tuFrnRLL4zfqRRuJepcz6nVS5QvIUSwZAC0iLkUg8tly0TOSGlvN24QVUPZDs71knrccwn75miGh-FrA

{
  "phone": "+998949092299",
  "code": "28755"

}



###create
POST  http://localhost:8081/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2Nzc1MTc3NjUsInBob25lIjoiOTk4OTAwOTY0NjQ4Iiwicm9sZSI6W251bGxdLCJleHAiOjE2Nzc2MDQxNjUsImlzcyI6ImRhc2hhdG9wIn0.iUcYfxrHoCqNUFC0tG0VaVMOB8dlWfh2q9xOf7zZIad2_kBDOq3w3F-76ZXXs8q07oLT0dZOUv65rVMbYCewVg

{
  "firstName": "Bahodir",
  "lastName": "Hurramov",
  "phone": "998900964649",
  "password": "123456",
  "roleList": ["ROLE_USER"]

}

### reset password request
PUT http://localhost:8081/api/v1/profile/password/reset/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzY4MjE5NTgsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3NjkwODM1OCwiaXNzIjoiZGFzaGF0b3AifQ.Qe6HI6LoKZVZOkvng0ELZBP11i9LP6LtsQOGXBqBmABmSAe8JtMsQh1RIA-a7ZdQndhf51UOlkOmxYNT1KHRAg


### reset password confirm
PUT http://localhost:8081/api/v1/profile/password/reset/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzY4MjE5NTgsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3NjkwODM1OCwiaXNzIjoiZGFzaGF0b3AifQ.Qe6HI6LoKZVZOkvng0ELZBP11i9LP6LtsQOGXBqBmABmSAe8JtMsQh1RIA-a7ZdQndhf51UOlkOmxYNT1KHRAg


{
  "code": "777063"
}



### change phone request
PUT http://localhost:8081/api/v1/profile/phone/change/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzY4MzA4OTksInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzY5MTcyOTksImlzcyI6ImRhc2hhdG9wIn0.6804xZ_uHqzqwCT1rCWWZFx_WD-239PDbL_myTsDbQp0pS-svYfuwRBg1f8vo3vxiRqE8Qh5f5X2Ox8cr-4xnA

{
  "newPhone": "998997795710"
}


### change phone confirm
PUT http://localhost:8081/api/v1/profile/phone/change/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzY4MzEzNTMsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzY5MTc3NTMsImlzcyI6ImRhc2hhdG9wIn0.OnmPONZQrfyMQO-j72Tkn9lMWxM-e_8Dn8cPymWgaLN4OjVSCacvjNr8gDLgdAj3ZrHKwanM5bEPEmrtGR1wcQ

{
  "code": "90830"
}


###get By Id
GET http://localhost:8081/api/v1/profile/admin/3f1bd185-25f3-4d8c-b9a7-b5764d49c6a1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzY4Mjc3NDYsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzY5MTQxNDYsImlzcyI6ImRhc2hhdG9wIn0.WhtYHpW6Y-dh6R_wJln1sP02ZonvTq2ot5TuU3Sg-nR_BfNRxrjQ-7OIidmOB6GZ3gEDvCOQxwfWtLk3yJG0NA


###delete
DELETE http://localhost:8081/api/v1/profile/admin/3f1bd185-25f3-4d8c-b9a7-b5764d49c6a1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzY4Mjc3NDYsInBob25lIjoiOTk4OTE1NzIxMjEzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzY5MTQxNDYsImlzcyI6ImRhc2hhdG9wIn0.WhtYHpW6Y-dh6R_wJln1sP02ZonvTq2ot5TuU3Sg-nR_BfNRxrjQ-7OIidmOB6GZ3gEDvCOQxwfWtLk3yJG0NA


###block
PUT http://localhost:8081/api/v1/profile/admin/block
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDgxODYsInBob25lIjoiOTk4OTExMjM0NTY3Iiwicm9sZSI6WyJST0xFX0FETUlOIl0sImV4cCI6MTY4MjgzNDU4NiwiaXNzIjoiZGFzaGF0b3AifQ.8h9-1ORbLWM_1L1aDA34R98gHtmIfwNJ_RlmQrhTy8nZ9F7vzlZbB4YCp9uURzhxuYyCJpIFEbMi4gasOxNYww

{
  "id": "5c224c20-4c12-466c-a0b6-ae7eca1dfe8f",
  "status": "ACTIVE"
}

### get Profile Pageable
POST http://localhost:8081/api/v1/profile/admin/filter?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDgxODYsInBob25lIjoiOTk4OTExMjM0NTY3Iiwicm9sZSI6WyJST0xFX0FETUlOIl0sImV4cCI6MTY4MjgzNDU4NiwiaXNzIjoiZGFzaGF0b3AifQ.8h9-1ORbLWM_1L1aDA34R98gHtmIfwNJ_RlmQrhTy8nZ9F7vzlZbB4YCp9uURzhxuYyCJpIFEbMi4gasOxNYww
Content-Type: application/json

{
  "firstName": "Toshmat"
}
