### Update profile
PUT http://localhost:8081/api/v1/profile/update/402880e58bbd8b90018bbd8f46260003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTk4MDY0NTMsImlkIjoiNDAyODgwZTU4YmJkOGI5MDAxOGJiZDhmNDYyNjAwMDMiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzAwNDExMjUzLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.xWwwO-kysPzbk5Rw9ZpJBYHctdnQuw7OTGp8zm4PsqwCx2i7dTrBcpQKJw7SoDW7DHiOHXwjLnGpeAfTLU4FJQ

{
  "name": "Bekzodjon",
  "surname": "Nosirovvv",
  "countryId": 6
}


### Get profile by id
GET http://localhost:8081/api/v1/profile/402880e88ad5dc2e018ad5de44250000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g

### PROD Get current profile
GET http://api.app.mazgi.uz/api/v1/profile/current
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTg5MjM5MTQsImlkIjoiODA4MGI3ZWY4YjYxNWY5OTAxOGI2MTc4ODkyMTAwMDAiLCJwaG9uZSI6Ijk5ODMzODczODQ4NyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk5NTI4NzE0LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.LPhYu-f3CbQFbhHpnbO6vS5OSUgMA4lN7uMREFMVhIWKWNpoSu6agnsh8MkG5lf7BiD3ddNQ0rFkDktuHMM1Mg

### DEV Get current profile
GET http://localhost:8081/api/v1/profile/current
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY1MDY1NTUsImlkIjoiNDAyODgwZTQ4YWZmYWE0MTAxOGFmZmFiNjIyMDAwMDAiLCJwaG9uZSI6Ijk5ODk0NDQ5NzM5NyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk3MTExMzU1LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.EE6LlickmJFuspkrmbcU3L2ERc9UMDzy-q9ehPMinaB3ZDzStqMLOnBHPasPk2fRGIGzAp3cDs78n1cGbxS7Uw




### Get profile filter
POST http://localhost:8081/api/v1/profile/filter
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzMzY3MjgsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDY5NDE1MjgsImlzcyI6IkphdmEgYmFja2VuZCJ9.ArAiyClsIt-iJEHX1HjijrlV4npeRlrlc6r1zVSKXB8u7Fq5wgdxerq6x4d29mlwytiSHgo2P4zGOewMKVfK9A
Content-Type: application/json


//{
//  "fromCreatedDate": "2023-08-08",
//  "toCreatedDate": "2023-09-28"
//}


### Delete profile
DELETE http://localhost:8081/api/v1/profile/8080b7ef8bb9951b018bb99818800000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g


### Delete profile gor PROD
DELETE http://api.app.mazgi.uz/api/v1/profile/8080b7ef8bb9951b018bb99818800000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDAwNTQyODIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDA2NTkwODIsImlzcyI6IkphdmEgYmFja2VuZCJ9.KD2ddFdoElK0-D4cW-kwEGej7jtbZrZdYZD6HkIO0HERwdDquHR4kqqAoxSNXz8ab8oCOSzTflZyEGzbeMCHAg



### Update profile phone
PUT http://localhost:8081/api/v1/profile/update-phone?phone=998944497397
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MjQ0NTAsImlkIjoiNDAyODgwZTg4YWQ1ZGMyZTAxOGFkNWRlNDQyNTAwMDAiLCJwaG9uZSI6Ijk5ODk0NDQ5NzM5NyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk2NDI5MjUwLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.w4rcDDov1b53HB2bQQi-QaLWhvljm0fU--z_0TJ0B36X8lb6qodAZHnXtEofcPmNNu9ij7Ffrjm761g3kqLHVw




### Update phone verification
PUT http://localhost:8081/api/v1/profile/phone-verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDUyNTUsImlkIjoiNDAyODgwZTg4YWQ1ZGMyZTAxOGFkNWRlNDQyNTAwMDAiLCJwaG9uZSI6Iis5OTg5NDQ0OTczOTciLCJyb2xlcyI6IlJPTEVfU1RVREVOVCIsImV4cCI6MTY5NjQxMDA1NSwiaXNzIjoiSmF2YSBiYWNrZW5kIn0.6g0Vy-tuFrnRLL4zfqRRuJepcz6nVS5QvIUSwZAC0iLkUg8tly0TOSGlvN24QVUPZDs71knrccwn75miGh-FrA

{
  "phone": "998908070176",
  "code": "41111"

}


### Update password
PUT http://localhost:8081/api/v1/profile/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MjQ0NTAsImlkIjoiNDAyODgwZTg4YWQ1ZGMyZTAxOGFkNWRlNDQyNTAwMDAiLCJwaG9uZSI6Ijk5ODk0NDQ5NzM5NyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNjk2NDI5MjUwLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.w4rcDDov1b53HB2bQQi-QaLWhvljm0fU--z_0TJ0B36X8lb6qodAZHnXtEofcPmNNu9ij7Ffrjm761g3kqLHVw

{
  "oldPassword": "123456",
  "newPassword": "111111",
  "confirmPassword": "111111"

}


### Change status
PUT http://localhost:8081/api/v1/profile/change-status/402880e88ad5dc2e018ad5de44250000?status=ACTIVE
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTU4MDYxMjYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY0MTA5MjYsImlzcyI6IkphdmEgYmFja2VuZCJ9.5i-zp9w0jxobonVZyh5ZjTVEVsHEkVUH0i7dLW19SDD60DVsYGpADR-QmzSBvbG3VHNVw6OncApX_JGf5S405g

### Get current profile
GET http://api.app.mazgi.uz/api/v1/profile/current
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTY1OTAyNTMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTcxOTUwNTMsImlzcyI6IkphdmEgYmFja2VuZCJ9.UrldW6gxB6D2T8ACp5KY6TElBnrxOBbj5pFtCN6vOysFsl_ojxrJhFrUw3DWqw1jkxgCtSx2jbriuzYJwxPSZw


### Get all
GET http://api.app.mazgi.uz/api/v1/profile/


###
DELETE http://localhost:8081/api/v1/profile/delete-account
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTk2MjI5ODksImlkIjoiNDAyODgwZWY4YmI5Njk2MDAxOGJiOTZiYWI1ZjAwMDAiLCJwaG9uZSI6Ijk5ODk5Nzc5NTcxMCIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzAwMjI3Nzg5LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.tO9OgyvEP2e74ofuGyzE90a5FuI5NgNDZQToPr0jSirK7SmYNJ-rlI4aExIefy3upHfIm3ZHzyfo5W1dtR-mXQ

### update lang
PUT http://api.app.mazgi.uz/api/v1/profile/update-lang?lang=uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDQ3ODI5MTcsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTU0Njg2MzAwMjgiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzA1Mzg3NzE3LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.gMwCSdqZWyvOD62ppMMb3A0mkzLXZyVM_8WPZzImBlyyLYbAYmSOnz3WTyuqm4-K8ndOixXN43xkgDdsPcGLXweyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDQ3ODI5MTcsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTU0Njg2MzAwMjgiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9TVFVERU5UIiwiZXhwIjoxNzA1Mzg3NzE3LCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.gMwCSdqZWyvOD62ppMMb3A0mkzLXZyVM_8WPZzImBlyyLYbAYmSOnz3WTyuqm4-K8ndOixXN43xkgDdsPcGLXw


### Change role ========== For Admin
PUT http://localhost:8081/api/v1/profile/change-role/8080b7ef8ba46236018bae5468630028
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0ODY0MzksImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDYwOTEyMzksImlzcyI6IkphdmEgYmFja2VuZCJ9.7_U5FPoLPgTMugHy1zNQyfhN7Hh0WVTmG8racrr9MQhxSNyM4BA73wIWo6JWi9SZt3uu3xHRp8Bdk_aVozaJkw
Content-Type: application/json

{
  "roles": [
    "ROLE_ADMIN"
  ]
}
