### Create
POST http://localhost:8081/api/v1/scholar-ship
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA3NjQxMzIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDEzNjg5MzIsImlzcyI6IkphdmEgYmFja2VuZCJ9.85ZQl0On1tm1rxDPQM8gRkgR-eyVljYSqKv5jhUQn8orPuj1fFv44TGT9_a5Qx7_aQtGJIfN-e-Rd5Y34AMIGg

{
  "name": "MIT grand",
  "description": "Kuzgi grandlar",
  "photoId": "8080b7ef8ba46236018badf59cd10019",
  "expiredDate": "2023-12-07",
  "startDate": "2022-10-01",
  "universityId": 3,
  "price": 1000,
  "degreeTypeList": ["Bachelor","MasterDegree"]
}

### Get By Id
GET http://localhost:8081/api/v1/scholar-ship/402880e58bed8185018bed8351160001/detail
Content-Type: application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA0OTY3NzgsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDExMDE1NzgsImlzcyI6IkphdmEgYmFja2VuZCJ9.Rf4wMqdFw1kFClIi-Q837DembphIb8cW6Ygr7vYb8WPE1BArthGgZXOCjiXPAPoS3oIrs7027zDejXwsdkPjMw

### Update
PUT http://localhost:8081/api/v1/scholar-ship/402881ee8be05498018be055287b0000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDAyNzUzNTAsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDA4ODAxNTAsImlzcyI6IkphdmEgYmFja2VuZCJ9.jVjL32thnYDLaj7oOWVhoRRElNJX2fEykr6BhIU1ozXFcKCyGLQY3PgWamoj8tSxeKz7VETIqsm0kh7Z3Z6BUg

{
  "name": "Harward grand",
  "description": "Kuzgi grandlar update",
  "expiredDate": "2024-10-07",
  "startDate": "2024-01-01",
  "price": 1400
}

### Delete By Id
DELETE http://localhost:8081/api/v1/scholar-ship/402880e58bed8185018bed8351160001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTcwMTg5NjIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTc2MjM3NjIsImlzcyI6IkphdmEgYmFja2VuZCJ9.kkbNqjcxNhBwrkP5dPauUYgvrkUqfDwtpHC0LHeKzg-KZzG5xG14svHm2g6CNcN0YExJTVm7idM3_vZaBc2zyA

### ScholarShip Filter
POST localhost:8081/api/v1/scholar-ship/filter?page=0&size=10
Content-Type: application/json

{
  "name": "it"
}

###
GET http://localhost:8081/api/v1/scholar-ship/top-grant
Accept-Language: uz

### GET ALL
GET http://localhost:8081/api/v1/scholar-ship/get-all
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA3NjQxMzIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDEzNjg5MzIsImlzcyI6IkphdmEgYmFja2VuZCJ9.85ZQl0On1tm1rxDPQM8gRkgR-eyVljYSqKv5jhUQn8orPuj1fFv44TGT9_a5Qx7_aQtGJIfN-e-Rd5Y34AMIGg

