###CREATE UNIVERSITY
POST http://localhost:8081/api/v1/university
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDAxMTYyNTYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDA3MjEwNTYsImlzcyI6IkphdmEgYmFja2VuZCJ9.UZH8Fuy76OqEWFLxgY10d1Ak3hTtgV05ooeLDvydKz5gI1EI0m6qhXMWuskWJSrvj0JJ9QpqLquP2LTwXXlOJw

{
  "name": "TATU2",
  "webSite": "www.tuit2.uz",
  "rating": 1,
  "countryId": 1,
  "photoId": "4028abb98bc471a5018bc475bbad0000",
  "degreeList": [
    "Bachelor",
    "MasterDegree"
  ]
}


###UPDATE UNIVERSITY
PUT http://localhost:8081/api/v1/university/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTYyNjI1NDIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY4NjczNDIsImlzcyI6IkphdmEgYmFja2VuZCJ9.y0zxd2v2--laY6asCk5-lk-2n7MrMy2QArgeydiUSA5tFCbldQKOSZn3ZiiA8U2fZn2KEDvRhm6uSSYDCcsS8A

{
  "name": "TATU",
  "webSite": "www.nuuz.uz",
  "rating": 1,
  "countryId": 1
}


###DELETE UNIVERSITY
DELETE http://localhost:8081/api/v1/university/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTYyNjI1NDIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY4NjczNDIsImlzcyI6IkphdmEgYmFja2VuZCJ9.y0zxd2v2--laY6asCk5-lk-2n7MrMy2QArgeydiUSA5tFCbldQKOSZn3ZiiA8U2fZn2KEDvRhm6uSSYDCcsS8A


###GET BY ID UNIVERSITY
GET http://localhost:8081/api/v1/university/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTk3ODYwNjMsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDAzOTA4NjMsImlzcyI6IkphdmEgYmFja2VuZCJ9.kWyofrDf9P2HGBc6Nj1ZmPJrmvpnCXGGXbuJJMzXMBqY_VKbfRNeMvZ83S_kSQLXpyCv9uyikII5GmuHuseGmw


### University filter
GET http://localhost:8081/api/v1/university/filter
Content-Type: application/json

{
}


### Get university detail by id
GET http://localhost:8081/api/v1/university/6/detail

### Get top university
GET http://localhost:8081/api/v1/university/top-university
Accept-Language: uz







