### CREATE UNIVERSITY
POST http://localhost:8081/api/v1/university
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NDI5NjgyMjgsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3NDM1NzMwMjksImlzcyI6IkphdmEgYmFja2VuZCJ9.Zk850e-bQfr5LHsvme-Db9JbP-Xeq8QeSvrqfeBInsxebMBPric4OfLIvp1sJqN0N0S83cYq4932rOq_lTx7dA

{
  "name": "BestUniversity",
  "webSite": "www.tuit3.uz",
  "rating": 1,
  "countryId": 1,
  "photoId": "872224bc-6717-48a0-a833-8febea3d8287_logo",
  "degreeList": [
    "Bachelor",
    "MasterDegree"
  ],
  "facultyIdList": [
    "76949a37-2d3b-4ce6-b4ab-9f67f1b561f3",
    "2a0f19d7-bce5-4cfb-8c75-5012adefa8dd",
    "846e13da-a586-4521-804b-e5d2800b5896"
  ]
}


###UPDATE UNIVERSITY
PUT http://localhost:8081/api/v1/university/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDA4OTQ5NjksImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDE0OTk3NjksImlzcyI6IkphdmEgYmFja2VuZCJ9.jyOGBIYCoPX02YsxKMLlIrkfjV9ah-wiHzwgjJuLwLw1II3Y4wZFoUJeIx67Dk1t0OdBpj5mSbQKymNE5qr97A

{
  "name": "Univer Math",
  "webSite": "www.univermath.com",
  "rating": 1,
  "countryId": 1,
  "degreeList": [
    "Bachelor",
    "MasterDegree"
  ],
  "facultyIdList": [
    "402880ea8bf4e7f6018bf4edd38b0000",
    "402880e48c01cac3018c01ce6e200000",
    "402880e48c01cac3018c01d1b0e40005"
  ]
}


###DELETE UNIVERSITY
DELETE http://localhost:8081/api/v1/university/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTYyNjI1NDIsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTY4NjczNDIsImlzcyI6IkphdmEgYmFja2VuZCJ9.y0zxd2v2--laY6asCk5-lk-2n7MrMy2QArgeydiUSA5tFCbldQKOSZn3ZiiA8U2fZn2KEDvRhm6uSSYDCcsS8A


###GET BY ID UNIVERSITY
GET http://localhost:8081/api/v1/university/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDQyNjk5MzYsImlkIjoiOTA5MTMzZmUtODFhZC00YWExLWI1ZmUtMzBkNDJkNzViYjNkIiwicGhvbmUiOiI5OTg5MzgwODA4MzEiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDQ4NzQ3MzYsImlzcyI6IkphdmEgYmFja2VuZCJ9.sqQtayHpvZuIlc8OD9owjXXk92F6xxUsrCt4eLZ-y37Kz1g_f_0ZeX515paM3F-5-UQ4PGxo-ptGVGMQA3-6lQ


### University filter
POST http://localhost:8081/api/v1/university/filter
Content-Type: application/json
Accept-Language: uz

{
  "name": "2"
}


### Get university detail by id
GET http://localhost:8081/api/v1/university/1/detail

### Get top university
GET http://localhost:8081/api/v1/university/top-university
Accept-Language: uz

### Get application university list for consulting. Consulting mobile first page
GET http://localhost:8081/api/v1/university/consulting/application
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDE2NTc5NjIsImlkIjoiODA4MGI3ZWY4YmE0NjIzNjAxOGJhZTRiMzA5NDAwMjEiLCJwaG9uZSI6Ijk5ODkxNTcyMTIxMyIsInJvbGVzIjoiUk9MRV9DT05TVUxUSU5HIiwiZXhwIjoxNzAyMjYyNzYyLCJpc3MiOiJKYXZhIGJhY2tlbmQifQ.Tr_ofDY84pXQ_e-xsANHnrZaEglwkeliCkISBxNixPdA1iGxKlVhLWeRJ91SO_577-IOXc31Rv8J1AoJVUr7QQ
Accept-Language: uz






