INSERT INTO country(id, name_uz, name_en, name_ru, created_date, visible)
values (7, 'Fransiya', 'France', 'Франция', now(), true),
       (8, 'AQSH', 'United States', 'Соединенные Штаты', now(), true),
       (9, 'Ispaniya', 'Spain', 'Испания', now(), true),
       (10, 'Italiya', 'Italy', 'Италия', now(), true),
       (11, 'Xitoy', 'China', 'Китай', now(), true),
       (12, 'Angliya', 'United Kingdom', 'Великобритания', now(), true),
       (13, 'Rossiya', 'Russia', 'Россия', now(), true),
       (14, 'Meksika', 'Mexico', 'Мексика', now(), true),
       (15, 'Kanada', 'Canada', 'Канада', now(), true),
       (16, 'Germaniya', 'Germany', 'Германия', now(), true),
       (17, 'Avstriya', 'Austria', 'Австрия', now(), true),
       (18, 'Polsha', 'Poland', 'Польша', now(), true),
       (19, 'Vengriya', 'Hungary', 'Венгрия', now(), true),
       (20, 'Gretsiya', 'Greece', 'Греция', now(), true),
       (21, 'Maroko', 'Morocco', 'Марокко', now(), true),
       (22, 'Janubiy Afrika', 'South Africa', 'Южная Африка', now(), true),
       (23, 'Jazoir', 'Algeria', 'Алжир', now(), true),
       (24, 'Mozambik', 'Mozambique', 'Мозамбик', now(), true),
       (25, 'Zimbabve', 'Zimbabwe', 'Зимбабве', now(), true),
       (26, 'Kenya', 'Kenya', 'Кения', now(), true),
       (27, 'Uganda', 'Uganda', 'Уганда', now(), true),
       (28, 'Saudiya Arabiston', 'Saudi Arabia', 'Саудовская Аравия', now(), true),
       (29, 'Birlashgan Arab Amirliklari', 'United Arab Emirates', 'Объединенные Арабские Эмираты', now(), true),
       (30, 'Misr', 'Egypt', 'Египет', now(), true),
       (31, 'Iran', 'Iran', 'Иран', now(), true),
       (32, 'Iordaniya', 'Jordan', 'Иордания', now(), true),
       (33, 'Isroil', 'Israel', 'Израиль', now(), true),
       (34, 'Braziliya', 'Brazil', 'Бразилия', now(), true),
       (35, 'Argentina', 'Argentina', 'Аргентина', now(), true),
       (36, 'Kolumbiya', 'Colombia', 'Колумбия', now(), true),
       (37, 'Chili', 'Chile', 'Чили', now(), true),
       (38, 'Peru', 'Peru', 'Перу', now(), true),
       (39, 'Gong Kong', 'Hong Kong', 'Гонконг', now(), true),
       (40, 'Xindiston', 'India', 'Индия', now(), true),
       (41, 'Tayland', 'Thailand', 'Таиланд', now(), true),
       (42, 'Janubiy Koreya', 'South Korea', 'Южная Корея', now(), true),
       (43, 'Yaponiya', 'Japan', 'Япония', now(), true),
       (44, 'Indonesiya', 'Indonesia', 'Индонезия', now(), true),
       (45, 'Turkiya', 'Turkey', 'Турция', now(), true),
       (46, 'Makau', 'Macau', 'Макао', now(), true),
       (47, 'Kipr', 'Cyprus', 'Кипр', now(), true),
       (48, 'Malayziya', 'Malaysia', 'Малайзия', now(), true),
       (49, 'Dominika Respublikasi', 'Dominican Republic', 'Доминиканская Республика', now(), true),
       (50, 'Qatar', 'Qatar', 'Катар', now(), true),
       (51, 'Oman', 'Oman', 'Оман', now(), true),
       (52, 'Bahrayn', 'Bahrain', 'Бахрейн', now(), true),
       (53, 'Senegal', 'Senegal', 'Сенегал', now(), true),
       (54, 'Namibiya', 'Namibia', 'Намибия', now(), true),
       (55, 'Avstraliya', 'Australia', 'Австралия', now(), true) ON CONFLICT (id) DO NOTHING;
SELECT setval('country_id_seq', max(id))
FROM country;